packages:
  - '.'

ignoredBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - core-js
  - core-js-pure
  - esbuild
  - prisma
  - sharp
